name: Deploy to ec2
on:
  push:
    branches:
      - feature/practice
jobs:
    build-test-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: darshana806/portfolio:latest-${{ github.sha }}
            - name: Deploy to ec2
              uses: appleboy/ssh-action@v1.0.3
              with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USER }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                        docker stop website || true
                        docker rm website || true
                        docker pull darshana806/portfolio:latest:${{ github.sha }}
                        docker run -d -p 80:80 darshana806/portfolio:latest:${{ github.sha }}
            
